ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: argocd.example.com
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - argocd.example.com
      secretName: argocd-tls

server:
  service:
    type: ClusterIP
    portHttp: 80
    portHttps: 443