yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: broker1.kafka.domain.name:9092,broker2.kafka.domain.name:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: kafka-ui.domain.name
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: domain-name
      hosts:
        - kafka-ui.domain.name