grafana:
  adminUser: admin
  adminPassword: strongpassword

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    path: /
    hosts:
      - grafana.domain.name
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.domain.name
  persistence:
    enabled: true
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    size: 10Gi

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    path: /
    hosts:
      - prometheus.domain.name
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.domain.name

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    path: /
    hosts:
      - alertmanager.domain.name
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.domain.name

# Enabling persistence for Prometheus
prometheusOperator:
  prometheus:
    persistence:
      enabled: true
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce
      size: 50Gi

prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: false

# Additional configuration for resource limits and requests
grafana:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi